<div id="gambar2" class="carousel slide" data-ride="carousel">	        
	<!-- Indicators -->
	<ul class="carousel-indicators">
		<li data-target="#gambar2" data-slide-to="0" class="active"></li>
		<li data-target="#gambar2" data-slide-to="1"></li>
		<li data-target="#gambar2" data-slide-to="2"></li>
	</ul>
			      
	<!-- The slideshow -->
	<div class="carousel-inner">
		<div class="carousel-item active">
	        <img src="assets/gabah1.jpeg" alt="Gambar - 1" width="100%" height="100%">
		</div>
		<div class="carousel-item">
		    <img src="assets/gabah2.jpeg" alt="Gambar - 2" width="100%" height="100%">
	    </div>
	    <div class="carousel-item">
		    <img src="assets/gabah3.jpeg" alt="Gambar - 3" width="100%" height="100%">
	    </div>		    
	</div>
	<!-- Left and right controls -->
	<a class="carousel-control-prev" href="#gambar2" data-slide="prev">
		<span class="carousel-control-prev-icon"></span>
	</a>		
	<a class="carousel-control-next" href="#gambar2" data-slide="next">
	    <span class="carousel-control-next-icon"></span>
	</a>
</div>	
<small>
	<p><i>(Sumber gambar: KKN-T 68)</i></p>
</small>
<div class="card-body">
	<h3 class="card-title">Usaha Gabah BUMDesa Makmur Sejahtera</h3>
	<p class="card-text" style="text-align: justify; text-indent: 0.5in;">
		
		<br>
		Sektor pertanian masih menjadi sumber pendapatan utama bagi masyarakat Desa Telang. Para masyarakat yang memiliki sawah dan hasil tani tidak perlu bingung memikirkan pendistribusian hasil taninya seperti gabah karena BUMDes menyediakan sarana distribusinya. Masyarakat juga bisa mengajukan bantuan modal kepada BUMDes untuk kemudian bekerja sama dalam mengelola hasil panen. Berikut daftar harga yang ditawarkan oleh BUMDes Telang:
		<br>
		<table class="table table-hover">
		  <thead>
		    <tr>
		      <th scope="col">Nomor</th>
		      <th scope="col">Jenis Hasil Pertanian</th>
		      <th scope="col">Harga Jual</th>
		      <th scope="col">Lingkup Penjualan</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <th scope="row">1</th>
		      <td>Gabah</td>
		      <td>Rp4500</td>
		      <td>Kabupaten Bangkalan</td>
		    </tr>
		    <tr>
		      <th scope="row">2</th>
		      <td>Beras</td>
		      <td>Rp8000</td>
		      <td>Desa Telang</td>
		    </tr>
		  </tbody>
		</table>
	</p>
</div>