<img src="assets/kolam1.jpeg" class="card-img-top" alt="...">
<small>
	<p><i>(Sumber gambar: KKN-T 68 dan Ketua BUMDesa)</i></p>
</small>
<div class="card-body">
	<h3 class="card-title">Proyek Pembangunan Kolam Renang Skala Nasional</h3>
	<p class="card-text" style="text-align: justify; text-indent: 0.5in;">
		BUMDesa Makmur Sejahtera membangun sebuah proyek besar untuk mengembakan ekonomi dan daya tarik masyarakat telang bahkan sampai bangkalan dengan membangun proyek kolam renang berstandard Nasional. Kolam Renang ini sendiri nantinya akan mempunyai PxL yaitu 20x40 M Sesuai dengan Standrad Nasional Indonesia.
		<br>
		<br>
		Tentu Saja Nantinya Kolam Renang ini akan menjadi salah satu pemasukan yang menjanjikan Bagi BUMDesa Makmur Sejahtera Karena nanti kolam renang ini akan di bukan untuk umum, dan juga dari pihak Perangkat desa dan pengurus BUMDES memiliki proyeksi untuk bekerja sama dengan beberapa instansi sekolah yang ada di sekitar desa Telang sampai kota Bangkalan.
		<br>
		<ol>
			<li>Pembangunan Batas Kolam</li>
			<div class="row">
				<div class="col-sm-2" style="text-align: justify;">
				</div>
				<div class="col-sm-9">
					<img src="assets/kolam2.jpeg" height="100%" width="100%">
					<p><i>(Sumber gambar: KKN-T 68 dan Ketua BUMDesa)</i></p>
					<br>
				</div>
			</div>
			<br>
			<br>
			<li>Pengurukan Tanah</li>
			<div class="row">
				<div class="col-sm-2" style="text-align: justify;">
				</div>
				<div class="col-sm-9">
					<img src="assets/kolam1.jpeg" height="100%" width="100%">
					<p><i>(Sumber gambar: KKN-T 68 dan Ketua BUMDesa)</i></p>
					<br>
				</div>
			</div>
			</div>
		</ol>
		<br>
		Nantinya juga ketika selesai pembangunan untuk air yang di buang dari kolam renang, akan di alirkan ke sungai yang ada di desa telang.Mari kita dukung bersama proyek besar yang di banguun oleh BUMDES dan juga Perangkat desa demi Kemajuan desa telang.
	</p>
</div>