<img src="assets/artikel3_1.jpg" class="card-img-top" alt="...">
<small>
	<p><i>(Sumber gambar: Tim Gugus Tugas Bungur)</i></p>
</small>
<div class="card-body">
	<h3 class="card-title">Kenali Bahaya Mutasi Virus Covid-19</h3>
	<p class="card-text" style="text-align: justify; text-indent: 0.5in;">
		Menurut Organisasi Kesehatan Dunia <i>(World Health Organization),</i> ketika suatu virus menyebar dan menyebabkan banyak infeksi, virus-virus tersebut akan bermutasi menjadi lebih kuat ataupun lebih lemah untuk menginfeksi makhluk hidup. Seperti halnya yang sedang kita alami saat ini, Covid-19 telah bermutasi menjadi varian-varian baru yang menyebar ke seluruh dunia. 
		<br>
		Meskipun begitu, perubahan atau mutasi pada virus tidak begitu saja membuat vaksin tidak efektif. Ketika muncul kasus ketika satu atau sebagian dari varian virus ini mampu menurunkan efektivitas vaksin, maka sangat memungkinkan untuk mengubah komposisi dari vaksin tersebut guna melawan varian-varian baru.
		<br>
		Jadi, selama ilmuwan masih harus banyak belajar dan meneliti virus ini, kita harus membantu dengan melakukan segala hal yang memungkinkan untuk menghentikan penyebaran virus Covid-19 dengan menerapkan protokol kesehatan serta mau mengikuti program vaksinasi.Lindungi diri serta orang-orang tercinta dengan patuh dan taat menjalankan prokes. Jangan lupa untuk selalu meningkatkan kekebalan imun tubuh dengan makan makanan bergizi seimbang, berolahraga, dan beristirahat dengan cukup.
	</p>
</div>