<!-- Footer -->
<footer style="background-image: linear-gradient(to bottom right,  #800C92, #EEC8F1)" class="text-center bg-light">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">

      <!-- Email -->
      <a class="btn btn-light btn-floating m-1" href="mailto:muhammadsyahrullah26@gmail.com" style="background-color: #F7C4FF;" role="button">
        <i class="icofont-email"></i>
      </a>

      <!-- Instagram -->
      <a class="btn btn-light btn-floating m-1" href="https://www.instagram.com/bicoftaste/" style="background-color: #F7C4FF;" role="button">
        <i class="icofont-instagram"></i>
      </a>

      <!-- WhatsApp -->
      <a class="btn btn-light btn-floating m-1" href="https://wa.me/6288289948758" style="background-color: #F7C4FF;" role="button">
        <i class="icofont-brand-whatsapp"></i>
      </a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <section class="">
      <p>
        <strong>Sistem Manajemen Moeanis</strong>
      </p>
    </section>
    <br>

    <!-- Section: Links -->
    
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 mb-8 mb-md-0">
          <h4 class="text-uppercase">Bekasi Timur Jawa Barat</h4>
          <h5 class="text-uppercase">Moeanis</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <strong><a class="text-dark"></a></strong>
            </li>
          </ul>
        </div>

      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-image: linear-gradient(to bottom right,  #ED98FA, #EEC8F1);">
    © 2022 Copyright:
    <a class="text-white" href="mailto:muhammadsyahrullah26@gmail.com">Moeanis</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->