<nav class="navbar navbar-expand-lg navbar-dark" style="background-image: linear-gradient(to bottom right,  #800C92, #EEC8F1)">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	   	Menu
	</button>

	<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	   	<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	   		<li class="nav-item active">
	        	<a class="nav-link" href="index.php?page=beranda">Beranda</a>
	      	</li>
			<li class="dropdown nav-item active" >
	        	<a class=" nav-link dropdown-toggle" data-toggle="dropdown" href="#">Input <span class="caret"></span></a>
				<ul class="dropdown-menu"style=" background-image: linear-gradient(to bottom right,  #ED98FA, #EEC8F1);>
					<li class="nav-item active" >
						<a class="nav-link text-dark" href="index.php?page=input"><b>Pemesanan</b></a>
					</li>
					<li class="nav-item active" >
						<a class="nav-link text-dark" href="index.php?page=keuangan"><b>Pengeluaran</b></a>
					</li>
				</ul>
	      	</li>
	      	<li class="dropdown nav-item active">
	        	<a class=" nav-link dropdown-toggle" data-toggle="dropdown" href="#">Riwayat<span class="caret"></span></a>
				<ul class="dropdown-menu " style=" background-image: linear-gradient(to bottom right,  #ED98FA, #EEC8F1); >
					<li class="nav-item active" >
						<a class="nav-link text-dark" href="index.php?page=profil"><b>Pemesanan</b></a>
					</li>
					<li class="nav-item active" >
						<a class="nav-link text-dark" href="index.php?page=rkeuangan"><b>Pengeluaran</b></a>
					</li>
				</ul>
	      	</li>
	      	<li class="nav-item active">
	       		<a class="nav-link" href="index.php?page=informasi">Produk</a>
	   		</li>

	  	</ul>
		<div class="row">
			<div class="bulat">
			</div>
		
		<h5 class="text-white-50" style="font-family: 'Permanent Marker', cursive;">Moeanis</h5>
		</div>
		

	</div>
</nav>